import Head from "next/head";
import Sidebar from "../components/Sidebar";
import { auth } from "../firebase";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div style={{ display: "flex" }}>
        <Sidebar />
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            width: "100%",
          }}
        >
          <p style={{ fontWeight: "600", fontSize: 40, marginRight: 20 }}>
            Welcome
          </p>
          <p style={{ fontWeight: "600", fontSize: 40 }}>{user.email}</p>
        </div>
      </div>
    </div>
  );
}
